title: Set up continuous integration with GitHub Actions
tagline: A brand new course on Learning Lab
description: Set up CI with GitHub Actions
template:
  repo: set-up-continuous-integration-with-github-actions-template
  name: set-up-continuous-integration-with-github-actions
before:
  - type: updateBranchProtection
  - type: createIssue
    title: There's a bug!
    body: bug.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
